#!/bin/sh

PREREQ=""

prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

. /scripts/functions

log_begin_msg "Flushing iptables rules"
# Accept all traffic first to avoid ssh lockdown via iptables firewall rules
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT

# Flush all iptables chains/Firewall rules
iptables -F

# Delete all iptables chains
iptables -X

# Flush all counters too
iptables -Z

# Flush and delete all nat and  mangle
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X
iptables -t raw -F
iptables -t raw -X
log_end_msg
