#!/bin/sh

PREREQ=""

prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

. /scripts/functions

log_begin_msg "Flushing nftables ruleset"
nft flush ruleset
log_end_msg
