#!/bin/sh
# Execute nft boot hook

PREREQ="iptables"

prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

nft -f /usr/share/stsbl/iserv-cryptsetup/nft/default-structure.nft

if [ -e "/etc/initramfs-tools/firewall.nft" ]
then
  nft -f /etc/initramfs-tools/firewall.nft
fi
