#!/bin/sh
# Execute iptables boot hook

PREREQ="udev nft-default"

prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

. /scripts/functions

if [ -e "/etc/initramfs-tools/iptables-commands.sh" ]
then
  log_begin_msg "Executing custom iptables commands"
  . /etc/initramfs-tools/iptables-commands.sh
  log_end_msg
fi
