#!/bin/sh
# Execute nft boot hook

PREREQ="iptables udev nft-default"

prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

. /scripts/functions

if [ -e "/etc/initramfs-tools/firewall.nft" ]
then
  log_begin_msg "Applying custom firewall.nft rules"
  nft -f /etc/initramfs-tools/firewall.nft
  log_end_msg
fi
