#!/bin/sh

PREREQ="udev"

prereqs()
{
     echo "$PREREQ"
}

case $1 in
prereqs)
     prereqs
     exit 0
     ;;
esac

. /scripts/functions

log_begin_msg "Applying default nftables structure"
nft -f /usr/share/stsbl/iserv-cryptsetup/nft/default-structure.nft
log_end_msg
