#!/bin/sh

show_message()
{
        if [ -x "/bin/plymouth" ]
        then
                plymouth display-message --text="$1"
        fi
        echo "$1"
}

export PCSCLITE_NO_POLKIT=1

killall pcscd gpg-agent scdaemon &> /dev/null
rm -rf /run/pcscd
mkdir -p -m0755 /run/pcscd

show_message "Initalizing Smartcard daemon ..." >&2
if pcscd --help | grep -q -- '^  --disable-polkit'
then
  pcscd --disable-polkit --foreground &
else
  pcscd --foreground &
fi

sleep 10
show_message "Smartcard daemon initalized" >&2

is_pinpad_reader()
{
    # 1. Get display name of reader from GPG
    # Example: "SCM Microsystems Inc. SPR 532 [CCID Interface] (51271922202191) 00 00"
    GPG_READER_FULL=$(gpg --homedir "$GNUPGHOME" --with-colons --card-status 2>/dev/null | awk -F: '$1 == "Reader" {print $2}')

    [ -z "$GPG_READER_FULL" ] && return 2

    # 2. Extract serial number from GPG reader string in clings
    # If no clings are there (e.g. YubiKey), set 'X' as flag for dummy value
    T_SER=$(echo "$GPG_READER_FULL" | grep -o "(.*)" | tr -d '()')
    [ -z "$T_SER" ] && T_SER="X"

    # 3. Check for  USB path in sysfs
    for dev_dir in /sys/bus/usb/devices/*
    do
        [ -f "$dev_dir/serial" ] || [ "$T_SER" = "X" ] || continue

        # Get serial number if available
        CURR_SER=$(cat "$dev_dir/serial" 2>/dev/null || echo "X")

        # Serial number matches OR it is a device which does not report serial numbers (e.g. Yubikey) (Check via Product)
        MATCH=
        if [ "$T_SER" != "X" ] && [ "$CURR_SER" = "$T_SER" ]
        then
            MATCH=1
        elif [ "$T_SER" = "X" ]
        then
            # YubiKeys does not have a serial number (reports 000000): Search name in GPG reader info
            USB_PROD=$(cat "$dev_dir/product" 2>/dev/null)
            [ -n "$USB_PROD" ] && echo "$GPG_READER_FULL" | grep -q "$USB_PROD" && MATCH=1
        fi

        if [ "$MATCH" ]
        then
            # Check interface .0 of USB device
            # $dev_dir/*:*.0/
            IF_DIR=$(ls -d "$dev_dir/"*:*.0 2>/dev/null | head -n 1)

            if [ -n "$IF_DIR" ] && [ -f "$IF_DIR/bInterfaceClass" ]; then
                I_CLASS=$(cat "$IF_DIR/bInterfaceClass" | tr -d 'x0')
                # Smartcard class (0b or 11)
                if [ "$I_CLASS" = "b" ] || [ "$I_CLASS" = "11" ]; then
                    # Pinpad indication: 3+ endpoints
                    if [ "$(cat "$IF_DIR/bNumEndpoints")" -ge 3 ]; then
                        return 0 # YES, pinpad detected (e.g. Cherry/SCM)
                    fi
                fi
            fi
            break
        fi
    done

    return 1 # NO, YubiKey (Composite) or other token without pinpad
}

decrypt_gpg()
{
        export GNUPGHOME="$(dirname "$1")"

        restart_counter=1
        failed=

        while [ "$restart_counter" -le 6 ] && ! gpg -q --no-tty --homedir "$GNUPGHOME" --card-status &> /dev/null
        do
                counter=1
                while [ "$counter" -le 20 ] && ! gpg -q --no-tty  --homedir "$GNUPGHOME" --card-status &> /dev/null
                do
                        show_message "Smartcard not up yet, waiting ..." >&2
                        sleep .5
                        if gpg --homedir "$GNUPGHOME" --card-status &> /dev/null
                        then
                                break 2
                        fi
                        counter=$((counter + 1))
                done
                if ! [ "$restart_counter" -le 6 ]
                then
                        show_message "Timeout while waiting for smartcard." >&2
                        sleep 1
                        failed=1
                elif [ "$restart_counter" -gt 1 ]
                then
                        show_message "Smartcard unresponsive, restarting gpg-agent ..." >&2
                        sleep 1
                fi

                killall gpg-agent gpg &> /dev/null
                restart_counter=$((restart_counter + 1))
        done

        if [ "$failed" ]
        then
                show_message "Smartcard did not come up in time. Cannot unlock using Smartcard, try recovery password instead."
                sleep 5
        fi

        KEY_ID="$(gpg --homedir "$GNUPGHOME" --with-colons --card-status | awk -F: '$1 == "fpr" { print $2 }' | head -n 1)"

        if is_pinpad_reader
        then
                show_message "Please use the pinpad of your cardreader for PIN entry to unlock LUKS partition." >&2
                sleep 2

                # Skip asking for symmetric password by sending empty STDIN
                DECRYPTED_DATA="$(echo | gpg --no-tty --homedir "$GNUPGHOME" --batch --pinentry-mode loopback --passphrase-fd 0 --try-secret-key "${KEY_ID}!" --ignore-mdc-error -d "$1")"

                if [ "$DECRYPTED_DATA" ] || [ "$?" -eq 0 ]
                then
                        echo -n "$DECRYPTED_DATA"
                        killall gpg-agent pcscd scdaemon &> /dev/null
                        return 0
                fi
        else
                show_message "Performing GPG key decryption ..." >&2
                if [ -n "$KEY_ID" ]
                then
                        # Card reader without pinpad, use askpass to retrieve PIN
                        if ! /lib/cryptsetup/askpass "Enter PIN for your cardreader: " | \
                                gpg -q --batch --homedir "$GNUPGHOME" \
                                --trustdb-name /dev/null --pinentry-mode loopback --passphrase-fd 0 --try-secret-key "${KEY_ID}!" --decrypt "$1"; then
                                return 1
                        fi
                else
                        # Try to decrypt with symmetric password as fallback
                        if ! /lib/cryptsetup/askpass "Enter passphrase for key $1: " | \
                                gpg -q --batch --homedir "$GNUPGHOME" \
                                --trustdb-name /dev/null --pinentry-mode loopback --passphrase-fd 0 --decrypt "$1"; then
                                return 1
                        fi
                fi

                killall gpg-agent pcscd scdaemon &> /dev/null

                if [ -x "/bin/plymouth" ]
                then
                        plymouth hide-message
                fi

                return 0
        fi
}

if [ ! -x /usr/bin/gpg ]; then
        show_message "$0: /usr/bin/gpg is not available" >&2
        exit 1
fi

if [ -z "$1" ]; then
        show_message "$0: missing key as argument" >&2
        exit 1
fi

decrypt_gpg "$1"
exit "$?"

