#!/bin/sh

export PCSCLITE_NO_POLKIT=1

killall pcscd gpg-agent scdaemon &> /dev/null
rm -rf /run/pcscd
mkdir -p -m0755 /run/pcscd

# Polkit support starting from Debian Trixie, which isn't available in initramfs
if pcscd --help | grep -q -- '^  --disable-polkit'
then
  pcscd --disable-polkit --foreground &
else
  pcscd --foreground &
fi

sleep 10

decrypt_gpg () {

        # we check for attachted cardreader
        # cardreaders with pinpad: they have to be attached before booting
        # for cardreaders without pinpad: just attach them later, if the script already
        # asks for Passphrase or PIN
        restart_counter=1
        failed=

        while [ "$restart_counter" -le 6 ] && ! gpg -q --no-tty --homedir "$(dirname $1)" --card-status &> /dev/null
        do
                counter=1
                while [ "$counter" -le 20 ] && ! gpg -q --no-tty  --homedir "$(dirname $1)" --card-status &> /dev/null
                do
                        echo "Smartcard not up yet, waiting ..." >&2
                        sleep .5
                        if gpg --homedir "$(dirname $1)" --card-status &> /dev/null
                        then
                                break 2
                        fi
                        counter=$((counter + 1))
                done
                if ! [ "$restart_counter" -le 6 ]
                then
                        echo "Timeout while waiting for smartcard." >&2
                        failed=1
                elif [ "$restart_counter" -gt 1 ]
                then
                        echo "Smartcard unresponsive, restarting gpg-agent ..." >&2
                fi

                killall gpp-agent gpg &> /dev/null
                restart_counter=$((restart_counter + 1))
        done

        if [ "$failed" ]
        then
                echo "Smartcard did not come up in time. Cannot unlock using Smartcard, try recovery password instead."
        fi

        if gpg -q --no-tty --homedir "$(dirname $1)" --card-status > /dev/null 2>&1 && sleep 2; then
                echo "Please use the pinpad of your cardreader for PIN entry." >&2

                KEY_ID="$(gpg --homedir "$(dirname $1)" --with-colons --card-status | awk -F: '$1 == "fpr" { print $2 }')"

                RETURN=1
                DECRYPTED_DATA="$(echo | gpg --no-tty --homedir "$(dirname $1)" --batch --pinentry-mode loopback --passphrase-fd 0 --try-secret-key "${KEY_ID}!" --ignore-mdc-error -d /etc/keys/cryptkey.gpg)"

                if [ "$DECRYPTED_DATA" ] || [ "$?" -eq 0 ]
                then
                        echo -n "$DECRYPTED_DATA"
                        RETURN=0
                fi

                killall gpg-agent pcscd scdaemon &> /dev/null

                return "$RETURN"
        else
                echo "Performing GPG key decryption ..." >&2
                if ! /lib/cryptsetup/askpass \
                        "Enter passphrase for key $1, or PIN for your cardreader: " | \
                        gpg -q --batch --homedir "$(dirname "$1")" \
                        --trustdb-name /dev/null --passphrase-fd 0 --decrypt "$1"; then
                        return 1
                fi
                killall gpg-agent pcscd scdaemon &> /dev/null

                return 0
        fi
}
 
if [ ! -x /usr/bin/gpg ]; then
        echo "$0: /usr/bin/gpg is not available" >&2
        exit 1
fi
 
if [ -z "$1" ]; then
        echo "$0: missing key as argument" >&2
        exit 1
fi
 
decrypt_gpg "$1"
exit $?


