#!/bin/sh
set -e
 
PREREQ="cryptroot"
 
prereqs()
{
        echo "$PREREQ"
}

install_lib()
{
  for lib in $(ldconfig -p | awk '$1 == "'"$1"'" { print $4 }')
  do
    copy_exec "$lib"
  done
}

install_executable()
{
  if [ -x "$1" ]
  then
    copy_exec "$1"
  fi
}

case $1 in
prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

# Unify run directory and create convenience symlink for GnuPG home
ln -sf /etc/keys "${DESTDIR}/.gnupg"
mkdir -p "${DESTDIR}/var"
ln -sf /run "${DESTDIR}/var/run"

# Hooks for loading Gnupg software and key into the initramfs
 
# Check whether cryptroot hook has installed decrypt_gnupg_sc script
if [ ! -x ${DESTDIR}/lib/cryptsetup/scripts/decrypt_gnupg_sc ] ; then
    exit 0
fi

# Install cryptroot key files into initramfs
keys=$(sed 's/^\(.*,\|\)key=//; s/,.*//' ${DESTDIR}/conf/conf.d/cryptroot)

if [ "${keys}" != "none" ]; then
    if [ -z "${keys}" ]; then
        echo "$0: Missing key files in ${DESTDIR}/conf/conf.d/cryptroot" >&2
        cat ${DESTDIR}/conf/conf.d/cryptroot >&2
        exit 1
    fi
    for key in ${keys} ; do
        keydir=$(dirname ${key})
        echo "I: GnuPG-encrypted key file $key is copied to initramfs." >&2
        if [ ! -d ${DESTDIR}/${keydir} ] ; then
            mkdir -p ${DESTDIR}/${keydir}
        fi
        chmod 700 ${DESTDIR}/${keydir}
        cp -p ${key} ${DESTDIR}/${key}
        cp -p ${keydir}/pubring.kbx ${DESTDIR}/${keydir}
        if [ -e ${keydir}/gpg.conf ] ; then
            cp -p ${keydir}/gpg.conf ${DESTDIR}/${keydir}
        fi
        echo "disable-ccid" >> "${DESTDIR}/${keydir}/scdaemon.conf"
        echo "pcsc-shared" >> "${DESTDIR}/${keydir}/scdaemon.conf"
    done
fi

# Install gnupg software
install_executable /usr/bin/gpg
install_executable /usr/bin/gpg
install_executable /usr/bin/gpg-agent

# install dirname
install_executable /usr/bin/dirname

# some more libs for pcscd
install_executable /usr/sbin/pcscd
install_executable /usr/lib/pcsc/drivers/serial/libccidtwin.so
install_executable /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
install_executable /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
install_executable /etc/libccid_Info.plist

install_lib "libpcsclite.so.1"
install_lib "libgcc_s.so.1"
install_lib "libpcsclite_real.so.1"

# we need some more stuff from gnupg
install_executable /usr/lib/gnupg/keyboxd

install_executable /usr/lib/gnupg/scdaemon
install_executable /usr/bin/gpg-card

install_executable /usr/lib/gnupg/gpg-auth
install_executable /usr/bin/gpgconf
install_executable /usr/bin/gpg-connect-agent
install_executable /usr/bin/pinentry
install_executable /usr/lib/gnupg/gpg-check-pattern
install_executable /usr/lib/gnupg/gpg-preset-passphrase
install_executable /usr/lib/gnupg/gpg-protect-tool
install_executable /usr/bin/dirmngr
install_executable /usr/bin/dirmngr-client
install_executable /usr/lib/gnupg/dirmngr_ldap

install_executable /usr/bin/gpg-mail-tube
install_executable /usr/bin/gpgparsemail
install_executable /usr/bin/gpgsplit
install_executable /usr/bin/gpgtar
install_executable /usr/bin/kbxutil
install_executable /usr/bin/lspgpot
install_executable /usr/bin/migrate-pubring-from-classic-gpg
install_executable /usr/bin/watchgnupg
install_executable /usr/lib/gnupg/gpg-pair-tool
install_executable /usr/sbin/addgnupghome
install_executable /usr/sbin/applygnupgdefaults

install_executable /usr/bin/gpgsm

install_executable /usr/bin/ATR_analysis
install_executable /usr/bin/gscriptor
install_executable /usr/bin/pcsc_scan
install_executable /usr/bin/scriptor

exit 0
